# Generated by Django 3.2.9 on 2023-12-04 18:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectnMember',
            new_name='ProjectMember',
        ),
    ]
