# Generated by Django 3.2.9 on 2023-12-04 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_rename_projectnmember_projectmember'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='creted_by',
            new_name='created_by',
        ),
    ]
