# Generated by Django 3.2.9 on 2023-11-12 20:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMemberInvite',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=150)),
                ('token', models.CharField(max_length=255)),
                ('accepted', models.BooleanField(default=False)),
                ('role', models.PositiveSmallIntegerField(choices=[(5, 'Owner'), (10, 'Admin'), (15, 'Member'), (20, 'Guest')], default=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_invite', to='organization.organization')),
            ],
            options={
                'verbose_name': 'Organization Member Invite',
                'verbose_name_plural': 'Organization Member Invites',
                'db_table': 'organization_member_invites',
                'ordering': ('-created_at',),
            },
        ),
    ]
