# Generated by Django 3.2.9 on 2023-11-12 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization', '0002_organizationmemberinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmemberinvite',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_invite_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmemberinvite',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Owner'), (10, 'Admin'), (15, 'Member'), (20, 'Guest')], default=20),
        ),
    ]
