# Generated by Django 3.2.9 on 2023-12-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_organizationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocument',
            name='size',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
