# Generated by Django 3.2.9 on 2023-12-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_organizationdocument_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationdocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
