# Generated by Django 3.2.9 on 2023-12-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(5, 'Published'), (10, 'Done'), (15, 'In progress'), (20, 'Todo')], default=20),
        ),
    ]
