# Generated by Django 3.2.9 on 2023-12-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_content_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentplatform',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
